### ISSUE TITLE
pyninjotiff is not Python 3 compatible

### ISSUE THREAD

**Issue by gerritholl** [pytroll/pyninjotiff#10]
Pyninjotiff is not Python 3 compatible, as evidenced by print statements.

On Python 3.7:

```
python -c "import pyninjotiff.ninjotiff"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/media/nas/x21324/miniconda3/envs/py37b/lib/python3.7/site-packages/pyninjotiff/ninjotiff.py", line 1077
    print ""
           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("")?
```

**Comment by djhoese** [comment]
@loreclem is there any chance that you will have time during the next workshop (whether you are attending or not) to help with this?

**Comment by loreclem** [comment]
Hi @djhoese, if I look at my agenda right now... I see little chance that I will be able to work on this during the PCW (even from remote). On the other hand, Marco Sassi will be there in person and he might be a topic for him. I already discussed this with him and he's ready to help.
